// Code generated by goctl. DO NOT EDIT.
// Source: asset.proto

package server

import (
	"context"
	"grpc-common/ucenter/types/asset"
	"ucenter/internal/logic"
	"ucenter/internal/svc"
)

type AssetServer struct {
	svcCtx *svc.ServiceContext
	asset.UnimplementedAssetServer
}

func NewAssetServer(svcCtx *svc.ServiceContext) *AssetServer {
	return &AssetServer{
		svcCtx: svcCtx,
	}
}

func (s *AssetServer) FindWalletBySymbol(ctx context.Context, in *asset.AssetReq) (*asset.MemberWallet, error) {
	l := logic.NewAssetLogic(ctx, s.svcCtx)
	return l.FindWalletBySymbol(in)
}
