// Code generated by goctl. DO NOT EDIT.
// Source: register.proto

package server

import (
	"context"
	"grpc-common/market/types/rate"
	"market/internal/logic"
	"market/internal/svc"
)

type ExchangeRateServer struct {
	svcCtx *svc.ServiceContext
	rate.UnimplementedExchangeRateServer
}

func (e *ExchangeRateServer) UsdRate(ctx context.Context, req *rate.RateReq) (*rate.RateRes, error) {
	l := logic.NewExchangeRateLogic(ctx, e.svcCtx)
	return l.UsdRate(req)
}

func NewExchangeRateServer(svcCtx *svc.ServiceContext) *ExchangeRateServer {
	return &ExchangeRateServer{
		svcCtx: svcCtx,
	}
}
