// Code generated by goctl. DO NOT EDIT.
// Source: register.proto

package server

import (
	"market/internal/svc"
)

type RegisterServer struct {
	svcCtx *svc.ServiceContext
	//register.UnimplementedRegisterServer
}

func NewRegisterServer(svcCtx *svc.ServiceContext) *RegisterServer {
	return &RegisterServer{
		svcCtx: svcCtx,
	}
}
