// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: rate.proto

package rate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExchangeRateClient is the client API for ExchangeRate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeRateClient interface {
	UsdRate(ctx context.Context, in *RateReq, opts ...grpc.CallOption) (*RateRes, error)
}

type exchangeRateClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeRateClient(cc grpc.ClientConnInterface) ExchangeRateClient {
	return &exchangeRateClient{cc}
}

func (c *exchangeRateClient) UsdRate(ctx context.Context, in *RateReq, opts ...grpc.CallOption) (*RateRes, error) {
	out := new(RateRes)
	err := c.cc.Invoke(ctx, "/rate.ExchangeRate/usdRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeRateServer is the server API for ExchangeRate service.
// All implementations must embed UnimplementedExchangeRateServer
// for forward compatibility
type ExchangeRateServer interface {
	UsdRate(context.Context, *RateReq) (*RateRes, error)
	mustEmbedUnimplementedExchangeRateServer()
}

// UnimplementedExchangeRateServer must be embedded to have forward compatible implementations.
type UnimplementedExchangeRateServer struct {
}

func (UnimplementedExchangeRateServer) UsdRate(context.Context, *RateReq) (*RateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsdRate not implemented")
}
func (UnimplementedExchangeRateServer) mustEmbedUnimplementedExchangeRateServer() {}

// UnsafeExchangeRateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeRateServer will
// result in compilation errors.
type UnsafeExchangeRateServer interface {
	mustEmbedUnimplementedExchangeRateServer()
}

func RegisterExchangeRateServer(s grpc.ServiceRegistrar, srv ExchangeRateServer) {
	s.RegisterService(&ExchangeRate_ServiceDesc, srv)
}

func _ExchangeRate_UsdRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeRateServer).UsdRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rate.ExchangeRate/usdRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeRateServer).UsdRate(ctx, req.(*RateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeRate_ServiceDesc is the grpc.ServiceDesc for ExchangeRate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeRate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rate.ExchangeRate",
	HandlerType: (*ExchangeRateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "usdRate",
			Handler:    _ExchangeRate_UsdRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rate.proto",
}
