// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"ucenter-api/internal/midd"
	"ucenter-api/internal/svc"
)

func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	//如果要有中间件 怎么办？
	register := NewRegisterHandler(serverCtx)
	registerGroup := r.Group()
	registerGroup.Post("/uc/register/phone", register.Register)
	registerGroup.Post("/uc/mobile/code", register.SendCode)

	loginGroup := r.Group()
	login := NewLoginHandler(serverCtx)
	loginGroup.Post("/uc/login", login.Login)
	loginGroup.Post("/uc/check/login", login.CheckLogin)

	assetGroup := r.Group()
	assetGroup.Use(midd.Auth(serverCtx.Config.JWT.AccessSecret))

	asset := NewAssetHandler(serverCtx)
	assetGroup.Post("/uc/asset/wallet/:coinName", asset.FindWalletBySymbol)
	assetGroup.Post("/uc/asset/wallet", asset.FindWallet)                 // 用户钱包信息
	assetGroup.Post("/uc/asset/wallet/reset-address", asset.ResetAddress) //重置钱包信息
	assetGroup.Post("/uc/asset/transaction/all", asset.FindTransaction)   // 交易记录

	approveGroup := r.Group()
	approve := NewApproveHandler(serverCtx)
	approveGroup.Use(midd.Auth(serverCtx.Config.JWT.AccessSecret))
	approveGroup.Post("/uc/approve/security/setting", approve.SecuritySetting) // 用户的安全设置

	withdrawGroup := r.Group()
	withdraw := NewWithdrawHandler(serverCtx)
	withdrawGroup.Use(midd.Auth(serverCtx.Config.JWT.AccessSecret))
	withdrawGroup.Post("/uc/withdraw/support/coin/info", withdraw.QueryWithdrawCoin) //提现币种详细信息
	withdrawGroup.Post("/uc/mobile/withdraw/code", withdraw.SengCode)                //提币时，需要先向手机发送验证码，确保安全
	withdrawGroup.Post("/uc/withdraw/apply/code", withdraw.WithdrawCode)             // 提现
	withdrawGroup.Post("/uc/withdraw/record", withdraw.Record)                       //提现记录
}
