// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"ucenter-api/internal/midd"
	"ucenter-api/internal/svc"
)

func RegisterHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	//如果要有中间件 怎么办？
	register := NewRegisterHandler(serverCtx)
	registerGroup := r.Group()
	registerGroup.Post("/uc/register/phone", register.Register)
	registerGroup.Post("/uc/mobile/code", register.SendCode)

	loginGroup := r.Group()
	login := NewLoginHandler(serverCtx)
	loginGroup.Post("/uc/login", login.Login)
	loginGroup.Post("/uc/check/login", login.CheckLogin)

	assetGroup := r.Group()
	assetGroup.Use(midd.Auth(serverCtx.Config.JWT.AccessSecret))

	asset := NewAssetHandler(serverCtx)
	assetGroup.Post("/uc/asset/wallet/:coinName", asset.FindWalletBySymbol)
	assetGroup.Post("/uc/asset/wallet", asset.FindWallet) // 用户钱包信息
}
