// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"github.com/zeromicro/go-zero/rest"
	"net/http"
)

type Routers struct {
	server      *rest.Server
	middlewares []rest.Middleware
}

func NewRouters(server *rest.Server) *Routers {
	return &Routers{
		server: server,
	}
}

func (r *Routers) Get(path string, httphandler http.HandlerFunc) {
	r.server.AddRoutes(
		rest.WithMiddlewares(
			r.middlewares,
			rest.Route{
				Method:  http.MethodGet,
				Path:    path,
				Handler: httphandler,
			}),
	)
}

func (r *Routers) Post(path string, httphandler http.HandlerFunc) {
	r.server.AddRoutes(
		rest.WithMiddlewares(
			r.middlewares,
			rest.Route{
				Method:  http.MethodPost,
				Path:    path,
				Handler: httphandler,
			}),
	)
}

func (r *Routers) Group() *Routers {
	return &Routers{
		server: r.server,
	}
}

func (r *Routers) Use(middle ...rest.Middleware) {
	r.middlewares = append(r.middlewares, middle...)
}
