// Code generated by goctl. DO NOT EDIT.
// Source: register.proto

package registerclient

import (
	"context"

	"ucenter/api/types/register"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CaptchaReq = register.CaptchaReq
	CodeReq    = register.CodeReq
	NoRes      = register.NoRes
	RegReq     = register.RegReq
	RegRes     = register.RegRes

	Register interface {
		RegisterByPhone(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error)
		SendCode(ctx context.Context, in *CodeReq, opts ...grpc.CallOption) (*NoRes, error)
	}

	defaultRegister struct {
		cli zrpc.Client
	}
)

func NewRegister(cli zrpc.Client) Register {
	return &defaultRegister{
		cli: cli,
	}
}

func (m *defaultRegister) RegisterByPhone(ctx context.Context, in *RegReq, opts ...grpc.CallOption) (*RegRes, error) {
	client := register.NewRegisterClient(m.cli.Conn())
	return client.RegisterByPhone(ctx, in, opts...)
}

func (m *defaultRegister) SendCode(ctx context.Context, in *CodeReq, opts ...grpc.CallOption) (*NoRes, error) {
	client := register.NewRegisterClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}
